name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Run apt update
      run: sudo apt update
    - name: Install dependencies
      run: sudo apt install -y cmake pkgconf autoconf libtool
    - name: Build JSON-C
      run: make jsonc
    - name: Install JSON-C
      run: sudo make jsonc_install
    - name: Build Common objects
      run: make
    - name: Install Common files such as config
      run: sudo make install
