name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Run apt update
      run: sudo apt update
    - name: Install LibYAML dependencies
      run: sudo apt install -y autoconf libtool
    - name: Build LibYAML
      run: sudo make libyaml
    - name: Build Common objects
      run: make
    - name: Install Common files such as config
      run: sudo make install
